# Generated by Django 5.2.11 on 2026-02-08 21:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Creator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("music", "Music"),
                            ("writing", "Written Word"),
                            ("visual", "Visual Art"),
                            ("film", "Film/Video"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "creation_date",
                    models.DateField(help_text="Date the work was created"),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="works",
                        to="core.creator",
                    ),
                ),
            ],
            options={
                "ordering": ["-registered_at"],
            },
        ),
    ]
