# Generated by Django 5.2.11 on 2026-02-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_work_file_upload"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="work",
            name="reviewer_notes",
            field=models.TextField(blank=True, help_text="Notes from the reviewer"),
        ),
        migrations.AddField(
            model_name="work",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_review", "Pending Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending_review",
                help_text="Review status of the work",
                max_length=20,
            ),
        ),
    ]
