# Generated by Django 5.2.11 on 2026-02-14 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_creator_credits_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creator",
            name="credits",
        ),
        migrations.RemoveField(
            model_name="work",
            name="reviewed_at",
        ),
        migrations.RemoveField(
            model_name="work",
            name="reviewer_notes",
        ),
        migrations.RemoveField(
            model_name="work",
            name="status",
        ),
    ]
