# Generated by Django 5.2.11 on 2026-02-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_creator_credits_remove_work_reviewed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="creator",
            name="credits",
            field=models.IntegerField(
                default=0, help_text="Number of work registrations available"
            ),
        ),
    ]
