# Generated by Django 5.2.11 on 2026-02-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_creator_credits"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="work_link",
            field=models.URLField(
                blank=True, help_text="Link to your work online (optional)", null=True
            ),
        ),
    ]
