# Generated by Django 5.2.11 on 2026-02-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_work_work_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="work_link",
            field=models.CharField(
                blank=True,
                help_text="Link to your work online (optional)",
                max_length=500,
                null=True,
            ),
        ),
    ]
